/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface ListBusinessCursorInterface extends utils.Interface {
  functions: {
    "_checkExistBusinessAccount()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "_checkExistBusinessAccount"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_checkExistBusinessAccount",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "_checkExistBusinessAccount",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ListBusinessCursor extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ListBusinessCursorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _checkExistBusinessAccount(overrides?: CallOverrides): Promise<[boolean]>;
  };

  _checkExistBusinessAccount(overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    _checkExistBusinessAccount(overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    _checkExistBusinessAccount(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    _checkExistBusinessAccount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
