/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cv from "./cv";
export type { cv };
export type { ListEmployee } from "./ListEmployee";
export type { ListEmployeeSkill } from "./ListEmployeeSkill";
