/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as business from "./business";
export type { business };
import type * as employee from "./employee";
export type { employee };
