/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface ListIIGRequestCursorInterface extends utils.Interface {
  functions: {
    "_checkExistIIGRequestLR(uint256,uint256)": FunctionFragment;
    "_checkExistIIGRequestSW(uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "_checkExistIIGRequestLR"
      | "_checkExistIIGRequestSW"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_checkExistIIGRequestLR",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "_checkExistIIGRequestSW",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "_checkExistIIGRequestLR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_checkExistIIGRequestSW",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ListIIGRequestCursor extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ListIIGRequestCursorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _checkExistIIGRequestLR(
      employeeId: PromiseOrValue<BigNumberish>,
      businessId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    _checkExistIIGRequestSW(
      employeeId: PromiseOrValue<BigNumberish>,
      businessId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  _checkExistIIGRequestLR(
    employeeId: PromiseOrValue<BigNumberish>,
    businessId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  _checkExistIIGRequestSW(
    employeeId: PromiseOrValue<BigNumberish>,
    businessId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    _checkExistIIGRequestLR(
      employeeId: PromiseOrValue<BigNumberish>,
      businessId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    _checkExistIIGRequestSW(
      employeeId: PromiseOrValue<BigNumberish>,
      businessId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    _checkExistIIGRequestLR(
      employeeId: PromiseOrValue<BigNumberish>,
      businessId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _checkExistIIGRequestSW(
      employeeId: PromiseOrValue<BigNumberish>,
      businessId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _checkExistIIGRequestLR(
      employeeId: PromiseOrValue<BigNumberish>,
      businessId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _checkExistIIGRequestSW(
      employeeId: PromiseOrValue<BigNumberish>,
      businessId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
