/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ListEmployeeCursor } from "./ListEmployeeCursor";
export type { ListEmployeeSkillCursor } from "./ListEmployeeSkillCursor";
