/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IIGData } from "./IIGData";
export type { ListIIGLRResult } from "./ListIIGLRResult";
export type { ListIIGSWResult } from "./ListIIGSWResult";
