/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ListIIGLRResult } from "./ListIIGLRResult";
export type { ListIIGRequest } from "./ListIIGRequest";
export type { ListIIGSWResult } from "./ListIIGSWResult";
