/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ListIIGRequestCursor,
  ListIIGRequestCursorInterface,
} from "../../../../cursor/business/iig/ListIIGRequestCursor";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "employeeId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "businessId",
        type: "uint256",
      },
    ],
    name: "_checkExistIIGRequestLR",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "employeeId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "businessId",
        type: "uint256",
      },
    ],
    name: "_checkExistIIGRequestSW",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ListIIGRequestCursor__factory {
  static readonly abi = _abi;
  static createInterface(): ListIIGRequestCursorInterface {
    return new utils.Interface(_abi) as ListIIGRequestCursorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ListIIGRequestCursor {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ListIIGRequestCursor;
  }
}
