/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ListBusinessCursor,
  ListBusinessCursorInterface,
} from "../../../cursor/business/ListBusinessCursor";

const _abi = [
  {
    inputs: [],
    name: "_checkExistBusinessAccount",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ListBusinessCursor__factory {
  static readonly abi = _abi;
  static createInterface(): ListBusinessCursorInterface {
    return new utils.Interface(_abi) as ListBusinessCursorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ListBusinessCursor {
    return new Contract(address, _abi, signerOrProvider) as ListBusinessCursor;
  }
}
