/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ListBigFiveCursor,
  ListBigFiveCursorInterface,
} from "../../../../cursor/employee/bigfive/ListBigFiveCursor";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "employeeId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "cid",
        type: "string",
      },
    ],
    name: "AddBigFive",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "employeeId",
        type: "uint256",
      },
    ],
    name: "isDiffSevenDays",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ListBigFiveCursor__factory {
  static readonly abi = _abi;
  static createInterface(): ListBigFiveCursorInterface {
    return new utils.Interface(_abi) as ListBigFiveCursorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ListBigFiveCursor {
    return new Contract(address, _abi, signerOrProvider) as ListBigFiveCursor;
  }
}
