/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface ListBigFiveCursorInterface extends utils.Interface {
  functions: {
    "isDiffSevenDays(uint256)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "isDiffSevenDays"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isDiffSevenDays",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "isDiffSevenDays",
    data: BytesLike
  ): Result;

  events: {
    "AddBigFive(uint256,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AddBigFive"): EventFragment;
}

export interface AddBigFiveEventObject {
  employeeId: BigNumber;
  cid: string;
}
export type AddBigFiveEvent = TypedEvent<
  [BigNumber, string],
  AddBigFiveEventObject
>;

export type AddBigFiveEventFilter = TypedEventFilter<AddBigFiveEvent>;

export interface ListBigFiveCursor extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ListBigFiveCursorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    isDiffSevenDays(
      employeeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  isDiffSevenDays(
    employeeId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    isDiffSevenDays(
      employeeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "AddBigFive(uint256,string)"(
      employeeId?: null,
      cid?: null
    ): AddBigFiveEventFilter;
    AddBigFive(employeeId?: null, cid?: null): AddBigFiveEventFilter;
  };

  estimateGas: {
    isDiffSevenDays(
      employeeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    isDiffSevenDays(
      employeeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
